import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Header from './components/ui/header'
import Footer from './components/ui/footer'
import LoginHeader from './components/ui/loginHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginHeader />
        <Footer />
      </body>
    </html>
  )
}
